version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: dummy-mosquitto
    ports:
      - "1884:1883"          # map host 1884 to container 1883
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    command: mosquitto -c /mosquitto/config/mosquitto.conf